### ISSUE TITLE
Redundant supression in EnricherConfigTest

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#2579]
## Description

The following `@SuppressWarnings("ResultOfMethodCallIgnored")` annotation is no longer needed:

https://github.com/eclipse-jkube/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/EnricherConfigTest.java#L36

We should remove this line.

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by invictus04** [comment]
hi @manusa Can i work on this issue? #2579

**Comment by rohanKanojia** [comment]
@invictus04 [`first-timers-only`](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) tagged issues are created for newcomers who are contributing to the project for the first time so that they can complete legal requirements and get familiar with project.

Now that you’ve completed that step, I would advise you to look into issues tagged with [`good first issue` / `help wanted` labels](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3A%22help+wanted%22) . Or maybe create some new issue if you find something that should be fixed

**Comment by git-ashug** [comment]
Hello @rohanKanojia , can I be assignef this issue as this will be my first time contributing to this project.

**Comment by git-ashug** [comment]
Hello, it seems this has already been taken care of with below commit:
https://github.com/eclipse-jkube/jkube/commit/b5dbf12b74d22edc07f6ffe056f5846beabc3a7f

**Comment by rohanKanojia** [comment]
@git-ashug : Thanks for checking this! Sorry for your time, feel free to pick up some other issue.
