### ISSUE TITLE
NpipeConnectionSocketFactory.createSocket The declared Exception exception is never thrown

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#2746]
### Description

The method [NpipeConnectionSocketFactory.createSocket](https://github.com/eclipse-jkube/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/win/NpipeConnectionSocketFactory.java#L36) declares an Exception that is never thrown.

The following line
https://github.com/eclipse-jkube/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/win/NpipeConnectionSocketFactory.java#L36

- [ ] should be changed to:

```java
    public Socket createSocket(HttpContext context) {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by mgurrie** [comment]
I am working on this issue and submitting a pr soon.

**Comment by rohanKanojia** [comment]
@mgurrie [`first-timers-only`](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) tagged issues are created for newcomers who are contributing to the project for the first time so that they can complete legal requirements and get familiar with project.

Now that you’ve completed that step, I would advise you to look into issues tagged with [`good first issue` / `help wanted` labels](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3A%22help+wanted%22) . Or maybe create some new issue if you find something that should be fixed.

**Comment by uiu252** [comment]
Hi, can i take this issue, first timer
