### ISSUE TITLE
Align Gradle plugin behavior with that what is introduced by PR 2714 in the Maven plugin

### ISSUE THREAD

**Issue by Jurrie** [eclipse-jkube/jkube#2773]
### Component

Kubernetes Gradle Plugin

### Is your enhancement related to a problem? Please describe

@manusa opted this in https://github.com/eclipse/jkube/pull/2714#discussion_r1512130966, but I'm not a Gradle user, so I don't feel like I'm the right person to do so.
@rohanKanojia [asked to create an issue instead](https://github.com/eclipse/jkube/pull/2714#issuecomment-1980898152), so here I am 😀

Basically, PR 2714 introduces an abstract class for all Helm goals. Before the PR was merged, the class `HelmMojo` served as both a base class for `HelmLintMojo` and `HelmPushMojo` _and_ as a Maven goal in itself. After the PR was merged, the `AbstractHelmMojo` class is the base class and the `HelmMojo` class is just the Maven goal.

### Describe the solution you'd like

A base class for Helm goals in the Gradle plugin.

**Comment by rohanKanojia** [comment]
@clarenced : Do you think you can pick up this one? Here we need to create an abstract class for all helm related tasks in https://github.com/eclipse-jkube/jkube/tree/master/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task in order to avoid duplication.

We need to do the same thing as done in #2714 but for `gradle-plugin/` module

**Comment by rohanKanojia** [comment]
@clarenced : Don't hesitate to ping me in case you need help.
