### ISSUE TITLE
OpenshiftBuildService Remove unused imports

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3020]
### Description

The class [OpenshiftBuildService](https://github.com/eclipse-jkube/jkube/blob/e86c429ee70ef10b6ab08ae993861603f90a6789/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java) has unused imports.

The following lines:
https://github.com/eclipse-jkube/jkube/blob/e86c429ee70ef10b6ab08ae993861603f90a6789/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java#L42

- [ ] should be removed

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by keerthinannepamula1** [comment]
@manusa Hey!! I'm new to the open source space. I managed to do around 3 PRs in my first week (this week). I'm searching java-based open source projects. May I work this issue? Atleast I'll try, I'll let you know if I can't.

**Comment by vijaybhagwat24** [comment]
may I work on this?

**Comment by rohanKanojia** [comment]
@keerthinannepamula1 Are you still working on this?

**Comment by rohanKanojia** [comment]
@vijaybhagwat24 [`first-timers-only`](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) tagged issues are created for newcomers who are contributing to the project for the first time so that they can complete legal requirements and get familiar with project.

Now that you’ve completed that step, I would advise you to look into issues tagged with [`good first issue` / `help wanted` labels](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3A%22help+wanted%22) . Or maybe create some new issue if you find something that should be fixed.

**Comment by pujakarakoti07** [comment]
I want to work on this issue, please assign this to me.

**Comment by rohanKanojia** [comment]
@pujakarakoti07 [`first-timers-only`](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) tagged issues are created for newcomers who are contributing to the project for the first time so that they can complete legal requirements and get familiar with project.

Now that you’ve completed that step, I would advise you to look into issues tagged with [`good first issue` / `help wanted` labels](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3A%22help+wanted%22) . Or maybe create some new issue if you find something that should be fixed.

**Comment by Shripad-Joshi** [comment]
Hello @rohanKanojia, I would like to work on this issue. Can you assign this issue to me?

**Comment by Shripad-Joshi** [comment]
Hello @rohanKanojia ,
Is this issue still unsolved, because I am not able see any import statement as  
import org.eclipse.jkube.kit.common.BuildRecreateMode; 
In specified path.
can you please help me.

**Comment by rohanKanojia** [comment]
@Shripad-Joshi : You're right. Looks like issue got outdated.

You can pick up some other issue.
