### ISSUE TITLE
HelidonGeneratorExposedPortsTest : Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3059]
### Component

JKube Kit

### Description
In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:
https://github.com/eclipse-jkube/jkube/blob/bfbf08d3e506b94f4e724e96e9ddcb230504b0ee/jkube-kit/jkube-kit-helidon/src/test/java/org/eclipse/jkube/helidon/generator/HelidonGeneratorExposedPortsTest.java#L70
users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 
### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [x] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

**Comment by kiratkumar47** [comment]
could you please assign this task to me?

**Comment by manusa** [comment]
Hi @kiratkumar47,
Thanks for showing interest for Eclipse JKube.
Since I think you haven't contributed yet to this repository, I'd advise you to start with a [`first-timers-only`](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only) issue so you can get familiar with the ECA and general contribution process.
