### ISSUE TITLE
SerializationTest is failing on windows

### ISSUE THREAD

**Issue by Sintivrousai** [eclipse-jkube/jkube#3113]
Part of #1338 

SerializationTest is failing after the latest commits.

[ERROR] Failures:
[ERROR]   SerializationTest$MultiLineStringsSerializedToScalarYamlBlocks.whenStringEndingWithNewline_thenAddBlockIndicatorInSerializedObject:240

I would like to be assigned for the issue since I have already done some research.

**Comment by rohanKanojia** [comment]
@Sintivrousai : Thanks for taking care of this issue. It looks like I missed updating this test while addressing PR review comments on https://github.com/eclipse-jkube/jkube/pull/3014 .

I think this test is trying to test invalid scenario. It's trying to serialize a multiline YAML scalar value with platform specific line endings (`\r\n` for Windows and `\n` for Linux). However, based on my observations while investigating #3014 a constructured object must contain `\n` to be correctly serialized into multiline scalar value.

I think we should update the test to not use `%n` and `String.format`, just directly use `\n`, we would slightly need to adjust the test name as well so that it's more clear:
```diff
-    void whenStringEndingWithNewline_thenAddBlockIndicatorInSerializedObject(@TempDir Path targetDir) throws IOException {
+    void unmarshal_whenStringEndingWithNewline_thenAddBlockIndicatorInSerializedObject(@TempDir Path targetDir) throws IOException {
       // Given
       final File targetFile = targetDir.resolve("cm.yaml").toFile();
       final ConfigMap source = new ConfigMapBuilder()
               .withNewMetadata()
-              .addToAnnotations("proxy.istio.io/config", String.format("proxyMetadata:%n    ISTIO_META_DNS_CAPTURE: \"false\"%nholdApplicationUntilProxyStarts: true\n"))
+              .addToAnnotations("proxy.istio.io/config", "proxyMetadata:\n    ISTIO_META_DNS_CAPTURE: \"false\"\nholdApplicationUntilProxyStarts: true\n")
```

Could you please check if test passes on your machine after making these changes?

**Comment by Sintivrousai** [comment]
Your adjustment worked. I have made a pull request.
