### ISSUE TITLE
HelmServiceDependencyUpdateIT is failing on windows

### ISSUE THREAD

**Issue by Sintivrousai** [eclipse-jkube/jkube#3121]
Part of #1338 

HelmServiceDependencyUpdateIT is failing on windows.

[ERROR] Failures:
[ERROR]   HelmServiceDependencyUpdateIT$ValidChart.whenConfigurationOptionsProvided_thenDependencyDownloaded:97->verifyHelmDependencyDownloaded:113
Argument(s) are different! Wanted:

Can I work on that?

**Comment by rohanKanojia** [comment]
Hello, Sorry I didn't test this on windows while adding this test in https://github.com/eclipse-jkube/jkube/pull/3098

Here are some code pointers to fix the test failures:

- `whenInvalidChartDirProvided_thenThrowException` : Test is failing due to a platform specific error message, maybe we can run this test only for Linux by adding `@EnabledOnOs(OS.LINUX)` annotation. You can also add same test that verifies message on Windows but that would only run on windows `@EnabledOnOs(OS.WINDOWS)`
- Other tests are failing due to helm CLI returning output with Line Feeds `\n` instead of CLRF `\r\n` on Windows. Here is screenshot 
![Screenshot 2024-06-04 213002](https://github.com/eclipse-jkube/jkube/assets/13834498/b087f0ec-3bac-4a60-aae0-fd3a600269c9)

Here is the code that takes output of `helm` command and splits it based on `System.lineSeparator()` : 
https://github.com/eclipse-jkube/jkube/blob/6f644f8745ad7cfd289f4706c9c2bceab152df29/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java#L186-L189


Test should pass when we update above mentioned code like this: 
```java
      String dependencyUpdateCommandOutput = dependencyUpdateCommand.call();
      String lineDelimiter = System.lineSeparator();
      if (!dependencyUpdateCommandOutput.contains(System.lineSeparator())) {
        lineDelimiter = "\n";
      }
      Arrays.stream(dependencyUpdateCommandOutput
          .split(lineDelimiter))
          .forEach(l -> logger.info("[[W]]%s", l));
```

**Comment by manusa** [comment]
Have we tried this:
```java

   Arrays.stream(dependencyUpdateCommand.call() 
       .split("\n\r?") 
       .forEach(l -> logger.info("[[W]]%s", l)); 
 } 
```

**Comment by rohanKanojia** [comment]
Yeah, this is better.

**Comment by rohanKanojia** [comment]
@Sintivrousai see my comment https://github.com/eclipse-jkube/jkube/issues/3121#issuecomment-2147909759 . You can configure test to be run only in linux by adding `@EnabledOnOs(OS.LINUX)` annotation

> - `whenInvalidChartDirProvided_thenThrowException` : Test is failing due to a platform-specific error message, maybe we can run this test only for Linux by adding `@EnabledOnOs(OS.LINUX)` annotation. You can also add same test that verifies message on Windows but that would only run on windows `@EnabledOnOs(OS.WINDOWS)`

**Comment by Sintivrousai** [comment]
oh i'm sorry i didn't see it
