### ISSUE TITLE
JibBuildServiceBuildTest.build_shouldLogBuiltTarImage is failing on windows

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3137]
### Component

JKube Kit

### Description
Related to #1338

:warning: A windows machine is required to reproduce and fix problems in this issue.

JibBuildServiceBuild.build_shouldLogBuiltTarImage is failing on windows with this message:
```
 C:\Users\rokum\AppData\Local\Temp\junit12211758810502474092\target\docker\test\foo\latest\tmp\jib-image.linux-amd64.tar successfully built
"
to contain:
  "/latest/tmp/jib-image.linux-amd64.tar successfully built" 
```

It's caused by this line where we're expecting path to be a linux filesystem path:
https://github.com/eclipse-jkube/jkube/blob/740279fed7fda5c43dbb130194beb9b263bb7d61/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServiceBuildTest.java#L162
Converting it to this should fix the issue: 
```
.contains(separatorsToSystem("/latest/tmp/jib-image.linux-amd64.tar successfully built"));
```

### Expected Behavior
JibBuildServiceBuildTest should pass on windows

### Acceptance Criteria
- [x] JibBuildServiceBuildTest should pass on windows

**Comment by l3002** [comment]
Hi @rohanKanojia : I can pick this up.

**Comment by l3002** [comment]
Hi @rohanKanojia : Sorry, I had to close the PR, I had created yesterday. Actually, I was having the same issue with `JibBuildServiceBuildTest` as the issue I was facing while working on #2841. I was finally able to resolve the issue. So, I've raised a new PR.

PS: The issue I was having was due to `Docker`, I re-installed docker and it worked like a charm. Thanks for your help.
