### ISSUE TITLE
VolumePermissionEnricherTest : Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3361]
### Component

JKube Kit

### Task description

In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:

https://github.com/eclipse-jkube/jkube/blob/c2c9a0cdd076fbeb25087a6598b448b5271d6293/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricherTest.java#L98

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 

### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [x] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

**Comment by ShivamChavan01** [comment]
hey @rohanKanojia  can i do it

**Comment by vijaybhagwat24** [comment]
kindly assign this to me.

**Comment by ShivamChavan01** [comment]
Hey @vijaybhagwat24 I was away for 4 days because of some interview I'm working on it rn. I'll finish it tomorrow sorry for not updating

**Comment by vijaybhagwat24** [comment]
hope you completed this.

**Comment by manusa** [comment]
Hi @vijaybhagwat24 
This one #2774 is free to take ;)

**Comment by ShivamChavan01** [comment]
I've been working on the issue #3361, specifically updating the VolumePermissionEnricherTest by replacing the deprecated asList() DSL method with asInstanceOf(InstanceOfAssertFactories.list(type.class)). During the process, I encountered a build failure due to missing Kubernetes dependencies, including io.fabric8.kubernetes.api.model and io.fabric8.kubernetes.client.

Could you please clarify whether I need to explicitly add these dependencies to the project, or if there’s a different setup for the build environment that I might be missing?

Also, I wanted to confirm if omitting the asInstanceOf() method within the singleElement() assertion is valid, or if it must be retained to ensure type safety. My understanding is that the asInstanceOf() method is essential for handling type inference, and removing it might cause issues in assertions on lists like VolumeMount.

Looking forward to your guidance on this!
![Screenshot 2024-09-15 133012](https://github.com/user-attachments/assets/f51356ab-d475-42ae-9f66-8cb796ba193a)

**Comment by manusa** [comment]
> Could you please clarify whether I need to explicitly add these dependencies to the project, or if there’s a different setup for the build environment that I might be missing?

You likely have some issue in your IDE setup.
Ignore those issues and try running the build, test, and so on, commands from the command line interface (CLI).

> Also, I wanted to confirm if omitting the asInstanceOf() method within the singleElement() assertion is valid, or if it must be retained to ensure type safety. My understanding is that the asInstanceOf() method is essential for handling type inference, and removing it might cause issues in assertions on lists like VolumeMount.

You need to do the replacements whenever the AssertJ `asList()` DSL method is invoked in the code regardless of whatever comes next.


Some tips for IntelliJ in case things are not working for you:

![image](https://github.com/user-attachments/assets/7673c24d-1adf-47f8-9377-89fe20e6e7f4)

Checking the `Delegate IDE build/run actions to Maven` and/or the `Skip Tests` and then reloading the project might help you with the issue in your screenshot.
