### ISSUE TITLE
KubernetesBuildTaskTest: The declared exception 'IOException' is never thrown

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3390]
### Description

The class [KubernetesBuildTaskTest](https://github.com/eclipse-jkube/jkube/blob/5931629ea51e061bd852cd75d8561a547bdf9711/gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java#L59) presents the issue: The declared exception 'IOException' is never thrown.

The following line:
https://github.com/eclipse-jkube/jkube/blob/5931629ea51e061bd852cd75d8561a547bdf9711/gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java#L59
should be changed to:

```java
  void setUp() {
```
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

**Comment by vikasrajputin** [comment]
Hello @manusa 

Can I grab this? I'm contributing for the first time to jkube, would like to start with this

**Comment by AhmedFaizanDev** [comment]
Hey, if this issue is still unclaimed, could I be assigned to work on it?

**Comment by rohanKanojia** [comment]
@AhmedFaizanDev  `first-timers-only`](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) tagged issues are created for newcomers who are contributing to the project for the first time so that they can complete legal requirements and get familiar with project.

Now that you’ve completed that step, I would advise you to look into issues tagged with [`good first issue` / `help wanted` labels](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3A%22help+wanted%22) . Or maybe create some new issue if you find something that should be fixed.

**Comment by vikasrajputin** [comment]
Hello @rohanKanojia 
PR is ready, could you please review it and share your feedback.
